// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/kele.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_kele_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{0}
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_kele_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// ChatEvent types: content, thinking, tool_call, tool_result, error, done
type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolResult    string                 `protobuf:"bytes,4,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_proto_kele_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{2}
}

func (x *ChatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ChatEvent) GetToolResult() string {
	if x != nil {
		return x.ToolResult
	}
	return ""
}

func (x *ChatEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_proto_kele_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestion    string                 `protobuf:"bytes,1,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_proto_kele_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type RunCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_proto_kele_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{5}
}

func (x *RunCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RunCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Quit          bool                   `protobuf:"varint,2,opt,name=quit,proto3" json:"quit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_proto_kele_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{6}
}

func (x *RunCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunCommandResponse) GetQuit() bool {
	if x != nil {
		return x.Quit
	}
	return false
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_kele_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_proto_kele_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MessageCount  int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	HistoryCount  int32                  `protobuf:"varint,4,opt,name=history_count,json=historyCount,proto3" json:"history_count,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_proto_kele_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{9}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionInfo) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionInfo) GetHistoryCount() int32 {
	if x != nil {
		return x.HistoryCount
	}
	return 0
}

func (x *SessionInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SessionInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_kele_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Providers       []string               `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	Model           string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SmallModel      string                 `protobuf:"bytes,5,opt,name=small_model,json=smallModel,proto3" json:"small_model,omitempty"`
	ActiveSessions  int32                  `protobuf:"varint,6,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	UptimeSeconds   int32                  `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	HeartbeatActive bool                   `protobuf:"varint,8,opt,name=heartbeat_active,json=heartbeatActive,proto3" json:"heartbeat_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_kele_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StatusResponse) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *StatusResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StatusResponse) GetSmallModel() string {
	if x != nil {
		return x.SmallModel
	}
	return ""
}

func (x *StatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetHeartbeatActive() bool {
	if x != nil {
		return x.HeartbeatActive
	}
	return false
}

type HeartbeatStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Active          bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	IntervalMinutes int32                  `protobuf:"varint,2,opt,name=interval_minutes,json=intervalMinutes,proto3" json:"interval_minutes,omitempty"`
	LastRun         string                 `protobuf:"bytes,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	LastDecision    string                 `protobuf:"bytes,4,opt,name=last_decision,json=lastDecision,proto3" json:"last_decision,omitempty"`
	TotalHeartbeats int32                  `protobuf:"varint,5,opt,name=total_heartbeats,json=totalHeartbeats,proto3" json:"total_heartbeats,omitempty"`
	ActionsTaken    int32                  `protobuf:"varint,6,opt,name=actions_taken,json=actionsTaken,proto3" json:"actions_taken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatStatusResponse) Reset() {
	*x = HeartbeatStatusResponse{}
	mi := &file_proto_kele_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatStatusResponse) ProtoMessage() {}

func (x *HeartbeatStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatStatusResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HeartbeatStatusResponse) GetIntervalMinutes() int32 {
	if x != nil {
		return x.IntervalMinutes
	}
	return 0
}

func (x *HeartbeatStatusResponse) GetLastRun() string {
	if x != nil {
		return x.LastRun
	}
	return ""
}

func (x *HeartbeatStatusResponse) GetLastDecision() string {
	if x != nil {
		return x.LastDecision
	}
	return ""
}

func (x *HeartbeatStatusResponse) GetTotalHeartbeats() int32 {
	if x != nil {
		return x.TotalHeartbeats
	}
	return 0
}

func (x *HeartbeatStatusResponse) GetActionsTaken() int32 {
	if x != nil {
		return x.ActionsTaken
	}
	return 0
}

type WorkspaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Goal          string                 `protobuf:"bytes,4,opt,name=goal,proto3" json:"goal,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,6,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Context       string                 `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	WorkDir       string                 `protobuf:"bytes,8,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Summary       string                 `protobuf:"bytes,9,opt,name=summary,proto3" json:"summary,omitempty"`
	TaskCount     int32                  `protobuf:"varint,10,opt,name=task_count,json=taskCount,proto3" json:"task_count,omitempty"`
	RunningCount  int32                  `protobuf:"varint,11,opt,name=running_count,json=runningCount,proto3" json:"running_count,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInfo) Reset() {
	*x = WorkspaceInfo{}
	mi := &file_proto_kele_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfo) ProtoMessage() {}

func (x *WorkspaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfo.ProtoReflect.Descriptor instead.
func (*WorkspaceInfo) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{13}
}

func (x *WorkspaceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkspaceInfo) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *WorkspaceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkspaceInfo) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *WorkspaceInfo) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *WorkspaceInfo) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *WorkspaceInfo) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WorkspaceInfo) GetTaskCount() int32 {
	if x != nil {
		return x.TaskCount
	}
	return 0
}

func (x *WorkspaceInfo) GetRunningCount() int32 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

func (x *WorkspaceInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Goal          string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,4,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Context       string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	WorkDir       string                 `protobuf:"bytes,6,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_proto_kele_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{14}
}

func (x *CreateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *CreateWorkspaceRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_proto_kele_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{15}
}

func (x *GetWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,4,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	Context       string                 `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_proto_kele_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *UpdateWorkspaceRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_proto_kele_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteWorkspaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*WorkspaceInfo       `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_proto_kele_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{18}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*WorkspaceInfo {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type TaskInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId     string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Prompt          string                 `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Priority        int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	DependsOn       []string               `protobuf:"bytes,8,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	AssignedSession string                 `protobuf:"bytes,9,opt,name=assigned_session,json=assignedSession,proto3" json:"assigned_session,omitempty"`
	Result          string                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	Error           string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	RetryCount      int32                  `protobuf:"varint,12,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries      int32                  `protobuf:"varint,13,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Tags            []string               `protobuf:"bytes,14,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt       string                 `protobuf:"bytes,16,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     string                 `protobuf:"bytes,17,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskInfo) Reset() {
	*x = TaskInfo{}
	mi := &file_proto_kele_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInfo) ProtoMessage() {}

func (x *TaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInfo.ProtoReflect.Descriptor instead.
func (*TaskInfo) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{19}
}

func (x *TaskInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskInfo) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *TaskInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskInfo) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *TaskInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskInfo) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *TaskInfo) GetAssignedSession() string {
	if x != nil {
		return x.AssignedSession
	}
	return ""
}

func (x *TaskInfo) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TaskInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskInfo) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *TaskInfo) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *TaskInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TaskInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TaskInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *TaskInfo) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	DependsOn     []string               `protobuf:"bytes,6,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,7,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Tags          []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	AutoReady     bool                   `protobuf:"varint,9,opt,name=auto_ready,json=autoReady,proto3" json:"auto_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_kele_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{20}
}

func (x *CreateTaskRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *CreateTaskRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *CreateTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTaskRequest) GetAutoReady() bool {
	if x != nil {
		return x.AutoReady
	}
	return false
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_kele_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{21}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_proto_kele_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UpdateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_kele_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,2,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	TagFilter     string                 `protobuf:"bytes,3,opt,name=tag_filter,json=tagFilter,proto3" json:"tag_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_proto_kele_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{24}
}

func (x *ListTasksRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListTasksRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

func (x *ListTasksRequest) GetTagFilter() string {
	if x != nil {
		return x.TagFilter
	}
	return ""
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskInfo            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_proto_kele_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{25}
}

func (x *ListTasksResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type StartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTaskRequest) Reset() {
	*x = StartTaskRequest{}
	mi := &file_proto_kele_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTaskRequest) ProtoMessage() {}

func (x *StartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTaskRequest.ProtoReflect.Descriptor instead.
func (*StartTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{26}
}

func (x *StartTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_proto_kele_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{27}
}

func (x *CancelTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RetryTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryTaskRequest) Reset() {
	*x = RetryTaskRequest{}
	mi := &file_proto_kele_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryTaskRequest) ProtoMessage() {}

func (x *RetryTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{28}
}

func (x *RetryTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlanWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goal          string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	WorkDir       string                 `protobuf:"bytes,2,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanWorkspaceRequest) Reset() {
	*x = PlanWorkspaceRequest{}
	mi := &file_proto_kele_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanWorkspaceRequest) ProtoMessage() {}

func (x *PlanWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*PlanWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{29}
}

func (x *PlanWorkspaceRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *PlanWorkspaceRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *PlanWorkspaceRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type PlanEventMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PlanJson      string                 `protobuf:"bytes,3,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanEventMsg) Reset() {
	*x = PlanEventMsg{}
	mi := &file_proto_kele_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanEventMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanEventMsg) ProtoMessage() {}

func (x *PlanEventMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanEventMsg.ProtoReflect.Descriptor instead.
func (*PlanEventMsg) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{30}
}

func (x *PlanEventMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlanEventMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PlanEventMsg) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

type ApprovePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanJson      string                 `protobuf:"bytes,1,opt,name=plan_json,json=planJson,proto3" json:"plan_json,omitempty"`
	Goal          string                 `protobuf:"bytes,2,opt,name=goal,proto3" json:"goal,omitempty"`
	WorkDir       string                 `protobuf:"bytes,3,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	AutoStart     bool                   `protobuf:"varint,4,opt,name=auto_start,json=autoStart,proto3" json:"auto_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePlanRequest) Reset() {
	*x = ApprovePlanRequest{}
	mi := &file_proto_kele_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePlanRequest) ProtoMessage() {}

func (x *ApprovePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePlanRequest.ProtoReflect.Descriptor instead.
func (*ApprovePlanRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{31}
}

func (x *ApprovePlanRequest) GetPlanJson() string {
	if x != nil {
		return x.PlanJson
	}
	return ""
}

func (x *ApprovePlanRequest) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *ApprovePlanRequest) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ApprovePlanRequest) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

type ApprovePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *WorkspaceInfo         `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Tasks         []*TaskInfo            `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePlanResponse) Reset() {
	*x = ApprovePlanResponse{}
	mi := &file_proto_kele_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePlanResponse) ProtoMessage() {}

func (x *ApprovePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePlanResponse.ProtoReflect.Descriptor instead.
func (*ApprovePlanResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{32}
}

func (x *ApprovePlanResponse) GetWorkspace() *WorkspaceInfo {
	if x != nil {
		return x.Workspace
	}
	return nil
}

func (x *ApprovePlanResponse) GetTasks() []*TaskInfo {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type BoardOverviewMsg struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	Workspaces     []*WorkspaceOverviewMsg `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	TotalTasks     int32                   `protobuf:"varint,2,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`
	RunningTasks   int32                   `protobuf:"varint,3,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	PendingTasks   int32                   `protobuf:"varint,4,opt,name=pending_tasks,json=pendingTasks,proto3" json:"pending_tasks,omitempty"`
	CompletedTasks int32                   `protobuf:"varint,5,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BoardOverviewMsg) Reset() {
	*x = BoardOverviewMsg{}
	mi := &file_proto_kele_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardOverviewMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardOverviewMsg) ProtoMessage() {}

func (x *BoardOverviewMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardOverviewMsg.ProtoReflect.Descriptor instead.
func (*BoardOverviewMsg) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{33}
}

func (x *BoardOverviewMsg) GetWorkspaces() []*WorkspaceOverviewMsg {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *BoardOverviewMsg) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *BoardOverviewMsg) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

func (x *BoardOverviewMsg) GetPendingTasks() int32 {
	if x != nil {
		return x.PendingTasks
	}
	return 0
}

func (x *BoardOverviewMsg) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

type WorkspaceOverviewMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Backlog       int32                  `protobuf:"varint,4,opt,name=backlog,proto3" json:"backlog,omitempty"`
	Ready         int32                  `protobuf:"varint,5,opt,name=ready,proto3" json:"ready,omitempty"`
	Running       int32                  `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	Done          int32                  `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	Failed        int32                  `protobuf:"varint,8,opt,name=failed,proto3" json:"failed,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,9,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceOverviewMsg) Reset() {
	*x = WorkspaceOverviewMsg{}
	mi := &file_proto_kele_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceOverviewMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceOverviewMsg) ProtoMessage() {}

func (x *WorkspaceOverviewMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceOverviewMsg.ProtoReflect.Descriptor instead.
func (*WorkspaceOverviewMsg) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{34}
}

func (x *WorkspaceOverviewMsg) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkspaceOverviewMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceOverviewMsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkspaceOverviewMsg) GetBacklog() int32 {
	if x != nil {
		return x.Backlog
	}
	return 0
}

func (x *WorkspaceOverviewMsg) GetReady() int32 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *WorkspaceOverviewMsg) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *WorkspaceOverviewMsg) GetDone() int32 {
	if x != nil {
		return x.Done
	}
	return 0
}

func (x *WorkspaceOverviewMsg) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *WorkspaceOverviewMsg) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type WatchBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchBoardRequest) Reset() {
	*x = WatchBoardRequest{}
	mi := &file_proto_kele_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBoardRequest) ProtoMessage() {}

func (x *WatchBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBoardRequest.ProtoReflect.Descriptor instead.
func (*WatchBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{35}
}

func (x *WatchBoardRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

type BoardEventMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardEventMsg) Reset() {
	*x = BoardEventMsg{}
	mi := &file_proto_kele_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardEventMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardEventMsg) ProtoMessage() {}

func (x *BoardEventMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardEventMsg.ProtoReflect.Descriptor instead.
func (*BoardEventMsg) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{36}
}

func (x *BoardEventMsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BoardEventMsg) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *BoardEventMsg) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BoardEventMsg) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *BoardEventMsg) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GetTaskLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskLogRequest) Reset() {
	*x = GetTaskLogRequest{}
	mi := &file_proto_kele_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskLogRequest) ProtoMessage() {}

func (x *GetTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskLogRequest.ProtoReflect.Descriptor instead.
func (*GetTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{37}
}

func (x *GetTaskLogRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetTaskLogRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TaskLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogEntry) Reset() {
	*x = TaskLogEntry{}
	mi := &file_proto_kele_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogEntry) ProtoMessage() {}

func (x *TaskLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogEntry.ProtoReflect.Descriptor instead.
func (*TaskLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{38}
}

func (x *TaskLogEntry) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TaskLogEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TaskLogEntry) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *TaskLogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TaskLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TaskLogEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogResponse) Reset() {
	*x = TaskLogResponse{}
	mi := &file_proto_kele_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogResponse) ProtoMessage() {}

func (x *TaskLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kele_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogResponse.ProtoReflect.Descriptor instead.
func (*TaskLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_kele_proto_rawDescGZIP(), []int{39}
}

func (x *TaskLogResponse) GetEntries() []*TaskLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_proto_kele_proto protoreflect.FileDescriptor

const file_proto_kele_proto_rawDesc = "" +
	"\n" +
	"\x10proto/kele.proto\x12\x04kele\"\a\n" +
	"\x05Empty\"B\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\"\x8d\x01\n" +
	"\tChatEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1f\n" +
	"\vtool_result\x18\x04 \x01(\tR\n" +
	"toolResult\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"F\n" +
	"\x0fCompleteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\"2\n" +
	"\x10CompleteResponse\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x01 \x01(\tR\n" +
	"suggestion\"L\n" +
	"\x11RunCommandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"@\n" +
	"\x12RunCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x12\n" +
	"\x04quit\x18\x02 \x01(\bR\x04quit\"*\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xad\x01\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12#\n" +
	"\rhistory_count\x18\x04 \x01(\x05R\fhistoryCount\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\"E\n" +
	"\x14ListSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.kele.SessionInfoR\bsessions\"\x96\x02\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1f\n" +
	"\vsmall_model\x18\x05 \x01(\tR\n" +
	"smallModel\x12'\n" +
	"\x0factive_sessions\x18\x06 \x01(\x05R\x0eactiveSessions\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x05R\ruptimeSeconds\x12)\n" +
	"\x10heartbeat_active\x18\b \x01(\bR\x0fheartbeatActive\"\xec\x01\n" +
	"\x17HeartbeatStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12)\n" +
	"\x10interval_minutes\x18\x02 \x01(\x05R\x0fintervalMinutes\x12\x19\n" +
	"\blast_run\x18\x03 \x01(\tR\alastRun\x12#\n" +
	"\rlast_decision\x18\x04 \x01(\tR\flastDecision\x12)\n" +
	"\x10total_heartbeats\x18\x05 \x01(\x05R\x0ftotalHeartbeats\x12#\n" +
	"\ractions_taken\x18\x06 \x01(\x05R\factionsTaken\"\xda\x02\n" +
	"\rWorkspaceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04goal\x18\x04 \x01(\tR\x04goal\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0emax_concurrent\x18\x06 \x01(\x05R\rmaxConcurrent\x12\x18\n" +
	"\acontext\x18\a \x01(\tR\acontext\x12\x19\n" +
	"\bwork_dir\x18\b \x01(\tR\aworkDir\x12\x18\n" +
	"\asummary\x18\t \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"task_count\x18\n" +
	" \x01(\x05R\ttaskCount\x12#\n" +
	"\rrunning_count\x18\v \x01(\x05R\frunningCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"\xbe\x01\n" +
	"\x16CreateWorkspaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12%\n" +
	"\x0emax_concurrent\x18\x04 \x01(\x05R\rmaxConcurrent\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x12\x19\n" +
	"\bwork_dir\x18\x06 \x01(\tR\aworkDir\"%\n" +
	"\x13GetWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xb7\x01\n" +
	"\x16UpdateWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0emax_concurrent\x18\x04 \x01(\x05R\rmaxConcurrent\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"(\n" +
	"\x16DeleteWorkspaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x16ListWorkspacesResponse\x123\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x13.kele.WorkspaceInfoR\n" +
	"workspaces\"\xf0\x03\n" +
	"\bTaskInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"depends_on\x18\b \x03(\tR\tdependsOn\x12)\n" +
	"\x10assigned_session\x18\t \x01(\tR\x0fassignedSession\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\f \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\r \x01(\x05R\n" +
	"maxRetries\x12\x12\n" +
	"\x04tags\x18\x0e \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\x10 \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\x11 \x01(\tR\vcompletedAt\"\x95\x02\n" +
	"\x11CreateTaskRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x06 \x03(\tR\tdependsOn\x12\x1f\n" +
	"\vmax_retries\x18\a \x01(\x05R\n" +
	"maxRetries\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x1d\n" +
	"\n" +
	"auto_ready\x18\t \x01(\bR\tautoReady\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa3\x01\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"y\n" +
	"\x10ListTasksRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12#\n" +
	"\rstatus_filter\x18\x02 \x01(\tR\fstatusFilter\x12\x1d\n" +
	"\n" +
	"tag_filter\x18\x03 \x01(\tR\ttagFilter\"9\n" +
	"\x11ListTasksResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.kele.TaskInfoR\x05tasks\"\"\n" +
	"\x10StartTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11CancelTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10RetryTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"l\n" +
	"\x14PlanWorkspaceRequest\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x12\x19\n" +
	"\bwork_dir\x18\x02 \x01(\tR\aworkDir\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\"Y\n" +
	"\fPlanEventMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tplan_json\x18\x03 \x01(\tR\bplanJson\"\x7f\n" +
	"\x12ApprovePlanRequest\x12\x1b\n" +
	"\tplan_json\x18\x01 \x01(\tR\bplanJson\x12\x12\n" +
	"\x04goal\x18\x02 \x01(\tR\x04goal\x12\x19\n" +
	"\bwork_dir\x18\x03 \x01(\tR\aworkDir\x12\x1d\n" +
	"\n" +
	"auto_start\x18\x04 \x01(\bR\tautoStart\"n\n" +
	"\x13ApprovePlanResponse\x121\n" +
	"\tworkspace\x18\x01 \x01(\v2\x13.kele.WorkspaceInfoR\tworkspace\x12$\n" +
	"\x05tasks\x18\x02 \x03(\v2\x0e.kele.TaskInfoR\x05tasks\"\xe2\x01\n" +
	"\x10BoardOverviewMsg\x12:\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x1a.kele.WorkspaceOverviewMsgR\n" +
	"workspaces\x12\x1f\n" +
	"\vtotal_tasks\x18\x02 \x01(\x05R\n" +
	"totalTasks\x12#\n" +
	"\rrunning_tasks\x18\x03 \x01(\x05R\frunningTasks\x12#\n" +
	"\rpending_tasks\x18\x04 \x01(\x05R\fpendingTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x05 \x01(\x05R\x0ecompletedTasks\"\xef\x01\n" +
	"\x14WorkspaceOverviewMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\abacklog\x18\x04 \x01(\x05R\abacklog\x12\x14\n" +
	"\x05ready\x18\x05 \x01(\x05R\x05ready\x12\x18\n" +
	"\arunning\x18\x06 \x01(\x05R\arunning\x12\x12\n" +
	"\x04done\x18\a \x01(\x05R\x04done\x12\x16\n" +
	"\x06failed\x18\b \x01(\x05R\x06failed\x12%\n" +
	"\x0emax_concurrent\x18\t \x01(\x05R\rmaxConcurrent\"6\n" +
	"\x11WatchBoardRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\"\x95\x01\n" +
	"\rBoardEventMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"B\n" +
	"\x11GetTaskLogRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x82\x01\n" +
	"\fTaskLogEntry\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"?\n" +
	"\x0fTaskLogResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.kele.TaskLogEntryR\aentries2\x94\f\n" +
	"\vKeleService\x12,\n" +
	"\x04Chat\x12\x11.kele.ChatRequest\x1a\x0f.kele.ChatEvent0\x01\x129\n" +
	"\bComplete\x12\x15.kele.CompleteRequest\x1a\x16.kele.CompleteResponse\x12?\n" +
	"\n" +
	"RunCommand\x12\x17.kele.RunCommandRequest\x1a\x18.kele.RunCommandResponse\x12>\n" +
	"\rCreateSession\x12\x1a.kele.CreateSessionRequest\x1a\x11.kele.SessionInfo\x128\n" +
	"\rDeleteSession\x12\x1a.kele.DeleteSessionRequest\x1a\v.kele.Empty\x127\n" +
	"\fListSessions\x12\v.kele.Empty\x1a\x1a.kele.ListSessionsResponse\x12.\n" +
	"\tGetStatus\x12\v.kele.Empty\x1a\x14.kele.StatusResponse\x12@\n" +
	"\x12GetHeartbeatStatus\x12\v.kele.Empty\x1a\x1d.kele.HeartbeatStatusResponse\x12D\n" +
	"\x0fCreateWorkspace\x12\x1c.kele.CreateWorkspaceRequest\x1a\x13.kele.WorkspaceInfo\x12>\n" +
	"\fGetWorkspace\x12\x19.kele.GetWorkspaceRequest\x1a\x13.kele.WorkspaceInfo\x12D\n" +
	"\x0fUpdateWorkspace\x12\x1c.kele.UpdateWorkspaceRequest\x1a\x13.kele.WorkspaceInfo\x12<\n" +
	"\x0fDeleteWorkspace\x12\x1c.kele.DeleteWorkspaceRequest\x1a\v.kele.Empty\x12;\n" +
	"\x0eListWorkspaces\x12\v.kele.Empty\x1a\x1c.kele.ListWorkspacesResponse\x125\n" +
	"\n" +
	"CreateTask\x12\x17.kele.CreateTaskRequest\x1a\x0e.kele.TaskInfo\x12/\n" +
	"\aGetTask\x12\x14.kele.GetTaskRequest\x1a\x0e.kele.TaskInfo\x128\n" +
	"\rUpdateTaskRPC\x12\x17.kele.UpdateTaskRequest\x1a\x0e.kele.TaskInfo\x122\n" +
	"\n" +
	"DeleteTask\x12\x17.kele.DeleteTaskRequest\x1a\v.kele.Empty\x12<\n" +
	"\tListTasks\x12\x16.kele.ListTasksRequest\x1a\x17.kele.ListTasksResponse\x123\n" +
	"\tStartTask\x12\x16.kele.StartTaskRequest\x1a\x0e.kele.TaskInfo\x125\n" +
	"\n" +
	"CancelTask\x12\x17.kele.CancelTaskRequest\x1a\x0e.kele.TaskInfo\x123\n" +
	"\tRetryTask\x12\x16.kele.RetryTaskRequest\x1a\x0e.kele.TaskInfo\x12A\n" +
	"\rPlanWorkspace\x12\x1a.kele.PlanWorkspaceRequest\x1a\x12.kele.PlanEventMsg0\x01\x12B\n" +
	"\vApprovePlan\x12\x18.kele.ApprovePlanRequest\x1a\x19.kele.ApprovePlanResponse\x127\n" +
	"\x10GetBoardOverview\x12\v.kele.Empty\x1a\x16.kele.BoardOverviewMsg\x12<\n" +
	"\n" +
	"WatchBoard\x12\x17.kele.WatchBoardRequest\x1a\x13.kele.BoardEventMsg0\x01\x12<\n" +
	"\n" +
	"GetTaskLog\x12\x17.kele.GetTaskLogRequest\x1a\x15.kele.TaskLogResponseB+Z)github.com/BlakeLiAFK/kele/internal/protob\x06proto3"

var (
	file_proto_kele_proto_rawDescOnce sync.Once
	file_proto_kele_proto_rawDescData []byte
)

func file_proto_kele_proto_rawDescGZIP() []byte {
	file_proto_kele_proto_rawDescOnce.Do(func() {
		file_proto_kele_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kele_proto_rawDesc), len(file_proto_kele_proto_rawDesc)))
	})
	return file_proto_kele_proto_rawDescData
}

var file_proto_kele_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_proto_kele_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: kele.Empty
	(*ChatRequest)(nil),             // 1: kele.ChatRequest
	(*ChatEvent)(nil),               // 2: kele.ChatEvent
	(*CompleteRequest)(nil),         // 3: kele.CompleteRequest
	(*CompleteResponse)(nil),        // 4: kele.CompleteResponse
	(*RunCommandRequest)(nil),       // 5: kele.RunCommandRequest
	(*RunCommandResponse)(nil),      // 6: kele.RunCommandResponse
	(*CreateSessionRequest)(nil),    // 7: kele.CreateSessionRequest
	(*DeleteSessionRequest)(nil),    // 8: kele.DeleteSessionRequest
	(*SessionInfo)(nil),             // 9: kele.SessionInfo
	(*ListSessionsResponse)(nil),    // 10: kele.ListSessionsResponse
	(*StatusResponse)(nil),          // 11: kele.StatusResponse
	(*HeartbeatStatusResponse)(nil), // 12: kele.HeartbeatStatusResponse
	(*WorkspaceInfo)(nil),           // 13: kele.WorkspaceInfo
	(*CreateWorkspaceRequest)(nil),  // 14: kele.CreateWorkspaceRequest
	(*GetWorkspaceRequest)(nil),     // 15: kele.GetWorkspaceRequest
	(*UpdateWorkspaceRequest)(nil),  // 16: kele.UpdateWorkspaceRequest
	(*DeleteWorkspaceRequest)(nil),  // 17: kele.DeleteWorkspaceRequest
	(*ListWorkspacesResponse)(nil),  // 18: kele.ListWorkspacesResponse
	(*TaskInfo)(nil),                // 19: kele.TaskInfo
	(*CreateTaskRequest)(nil),       // 20: kele.CreateTaskRequest
	(*GetTaskRequest)(nil),          // 21: kele.GetTaskRequest
	(*UpdateTaskRequest)(nil),       // 22: kele.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),       // 23: kele.DeleteTaskRequest
	(*ListTasksRequest)(nil),        // 24: kele.ListTasksRequest
	(*ListTasksResponse)(nil),       // 25: kele.ListTasksResponse
	(*StartTaskRequest)(nil),        // 26: kele.StartTaskRequest
	(*CancelTaskRequest)(nil),       // 27: kele.CancelTaskRequest
	(*RetryTaskRequest)(nil),        // 28: kele.RetryTaskRequest
	(*PlanWorkspaceRequest)(nil),    // 29: kele.PlanWorkspaceRequest
	(*PlanEventMsg)(nil),            // 30: kele.PlanEventMsg
	(*ApprovePlanRequest)(nil),      // 31: kele.ApprovePlanRequest
	(*ApprovePlanResponse)(nil),     // 32: kele.ApprovePlanResponse
	(*BoardOverviewMsg)(nil),        // 33: kele.BoardOverviewMsg
	(*WorkspaceOverviewMsg)(nil),    // 34: kele.WorkspaceOverviewMsg
	(*WatchBoardRequest)(nil),       // 35: kele.WatchBoardRequest
	(*BoardEventMsg)(nil),           // 36: kele.BoardEventMsg
	(*GetTaskLogRequest)(nil),       // 37: kele.GetTaskLogRequest
	(*TaskLogEntry)(nil),            // 38: kele.TaskLogEntry
	(*TaskLogResponse)(nil),         // 39: kele.TaskLogResponse
}
var file_proto_kele_proto_depIdxs = []int32{
	9,  // 0: kele.ListSessionsResponse.sessions:type_name -> kele.SessionInfo
	13, // 1: kele.ListWorkspacesResponse.workspaces:type_name -> kele.WorkspaceInfo
	19, // 2: kele.ListTasksResponse.tasks:type_name -> kele.TaskInfo
	13, // 3: kele.ApprovePlanResponse.workspace:type_name -> kele.WorkspaceInfo
	19, // 4: kele.ApprovePlanResponse.tasks:type_name -> kele.TaskInfo
	34, // 5: kele.BoardOverviewMsg.workspaces:type_name -> kele.WorkspaceOverviewMsg
	38, // 6: kele.TaskLogResponse.entries:type_name -> kele.TaskLogEntry
	1,  // 7: kele.KeleService.Chat:input_type -> kele.ChatRequest
	3,  // 8: kele.KeleService.Complete:input_type -> kele.CompleteRequest
	5,  // 9: kele.KeleService.RunCommand:input_type -> kele.RunCommandRequest
	7,  // 10: kele.KeleService.CreateSession:input_type -> kele.CreateSessionRequest
	8,  // 11: kele.KeleService.DeleteSession:input_type -> kele.DeleteSessionRequest
	0,  // 12: kele.KeleService.ListSessions:input_type -> kele.Empty
	0,  // 13: kele.KeleService.GetStatus:input_type -> kele.Empty
	0,  // 14: kele.KeleService.GetHeartbeatStatus:input_type -> kele.Empty
	14, // 15: kele.KeleService.CreateWorkspace:input_type -> kele.CreateWorkspaceRequest
	15, // 16: kele.KeleService.GetWorkspace:input_type -> kele.GetWorkspaceRequest
	16, // 17: kele.KeleService.UpdateWorkspace:input_type -> kele.UpdateWorkspaceRequest
	17, // 18: kele.KeleService.DeleteWorkspace:input_type -> kele.DeleteWorkspaceRequest
	0,  // 19: kele.KeleService.ListWorkspaces:input_type -> kele.Empty
	20, // 20: kele.KeleService.CreateTask:input_type -> kele.CreateTaskRequest
	21, // 21: kele.KeleService.GetTask:input_type -> kele.GetTaskRequest
	22, // 22: kele.KeleService.UpdateTaskRPC:input_type -> kele.UpdateTaskRequest
	23, // 23: kele.KeleService.DeleteTask:input_type -> kele.DeleteTaskRequest
	24, // 24: kele.KeleService.ListTasks:input_type -> kele.ListTasksRequest
	26, // 25: kele.KeleService.StartTask:input_type -> kele.StartTaskRequest
	27, // 26: kele.KeleService.CancelTask:input_type -> kele.CancelTaskRequest
	28, // 27: kele.KeleService.RetryTask:input_type -> kele.RetryTaskRequest
	29, // 28: kele.KeleService.PlanWorkspace:input_type -> kele.PlanWorkspaceRequest
	31, // 29: kele.KeleService.ApprovePlan:input_type -> kele.ApprovePlanRequest
	0,  // 30: kele.KeleService.GetBoardOverview:input_type -> kele.Empty
	35, // 31: kele.KeleService.WatchBoard:input_type -> kele.WatchBoardRequest
	37, // 32: kele.KeleService.GetTaskLog:input_type -> kele.GetTaskLogRequest
	2,  // 33: kele.KeleService.Chat:output_type -> kele.ChatEvent
	4,  // 34: kele.KeleService.Complete:output_type -> kele.CompleteResponse
	6,  // 35: kele.KeleService.RunCommand:output_type -> kele.RunCommandResponse
	9,  // 36: kele.KeleService.CreateSession:output_type -> kele.SessionInfo
	0,  // 37: kele.KeleService.DeleteSession:output_type -> kele.Empty
	10, // 38: kele.KeleService.ListSessions:output_type -> kele.ListSessionsResponse
	11, // 39: kele.KeleService.GetStatus:output_type -> kele.StatusResponse
	12, // 40: kele.KeleService.GetHeartbeatStatus:output_type -> kele.HeartbeatStatusResponse
	13, // 41: kele.KeleService.CreateWorkspace:output_type -> kele.WorkspaceInfo
	13, // 42: kele.KeleService.GetWorkspace:output_type -> kele.WorkspaceInfo
	13, // 43: kele.KeleService.UpdateWorkspace:output_type -> kele.WorkspaceInfo
	0,  // 44: kele.KeleService.DeleteWorkspace:output_type -> kele.Empty
	18, // 45: kele.KeleService.ListWorkspaces:output_type -> kele.ListWorkspacesResponse
	19, // 46: kele.KeleService.CreateTask:output_type -> kele.TaskInfo
	19, // 47: kele.KeleService.GetTask:output_type -> kele.TaskInfo
	19, // 48: kele.KeleService.UpdateTaskRPC:output_type -> kele.TaskInfo
	0,  // 49: kele.KeleService.DeleteTask:output_type -> kele.Empty
	25, // 50: kele.KeleService.ListTasks:output_type -> kele.ListTasksResponse
	19, // 51: kele.KeleService.StartTask:output_type -> kele.TaskInfo
	19, // 52: kele.KeleService.CancelTask:output_type -> kele.TaskInfo
	19, // 53: kele.KeleService.RetryTask:output_type -> kele.TaskInfo
	30, // 54: kele.KeleService.PlanWorkspace:output_type -> kele.PlanEventMsg
	32, // 55: kele.KeleService.ApprovePlan:output_type -> kele.ApprovePlanResponse
	33, // 56: kele.KeleService.GetBoardOverview:output_type -> kele.BoardOverviewMsg
	36, // 57: kele.KeleService.WatchBoard:output_type -> kele.BoardEventMsg
	39, // 58: kele.KeleService.GetTaskLog:output_type -> kele.TaskLogResponse
	33, // [33:59] is the sub-list for method output_type
	7,  // [7:33] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_kele_proto_init() }
func file_proto_kele_proto_init() {
	if File_proto_kele_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kele_proto_rawDesc), len(file_proto_kele_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kele_proto_goTypes,
		DependencyIndexes: file_proto_kele_proto_depIdxs,
		MessageInfos:      file_proto_kele_proto_msgTypes,
	}.Build()
	File_proto_kele_proto = out.File
	file_proto_kele_proto_goTypes = nil
	file_proto_kele_proto_depIdxs = nil
}
