// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: kele.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeleService_Chat_FullMethodName               = "/kele.KeleService/Chat"
	KeleService_Complete_FullMethodName           = "/kele.KeleService/Complete"
	KeleService_RunCommand_FullMethodName         = "/kele.KeleService/RunCommand"
	KeleService_CreateSession_FullMethodName      = "/kele.KeleService/CreateSession"
	KeleService_DeleteSession_FullMethodName      = "/kele.KeleService/DeleteSession"
	KeleService_ListSessions_FullMethodName       = "/kele.KeleService/ListSessions"
	KeleService_GetStatus_FullMethodName          = "/kele.KeleService/GetStatus"
	KeleService_GetHeartbeatStatus_FullMethodName = "/kele.KeleService/GetHeartbeatStatus"
)

// KeleServiceClient is the client API for KeleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeleService is the main daemon gRPC service.
// All client modes (TUI, Agent) communicate with the daemon through this service.
type KeleServiceClient interface {
	// Chat sends a message and receives streaming response events.
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	// Complete performs AI input completion using the small model.
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// RunCommand executes a slash command within a session.
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error)
	// CreateSession creates a new chat session on the daemon.
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	// DeleteSession removes a session.
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*Empty, error)
	// ListSessions returns all active sessions.
	ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// GetStatus returns daemon status information.
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	// GetHeartbeatStatus returns heartbeat system status.
	GetHeartbeatStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartbeatStatusResponse, error)
}

type keleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeleServiceClient(cc grpc.ClientConnInterface) KeleServiceClient {
	return &keleServiceClient{cc}
}

func (c *keleServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeleService_ServiceDesc.Streams[0], KeleService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeleService_ChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *keleServiceClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, KeleService_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keleServiceClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCommandResponse)
	err := c.cc.Invoke(ctx, KeleService_RunCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keleServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, KeleService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keleServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, KeleService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keleServiceClient) ListSessions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, KeleService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keleServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, KeleService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keleServiceClient) GetHeartbeatStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartbeatStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatStatusResponse)
	err := c.cc.Invoke(ctx, KeleService_GetHeartbeatStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeleServiceServer is the server API for KeleService service.
// All implementations must embed UnimplementedKeleServiceServer
// for forward compatibility.
//
// KeleService is the main daemon gRPC service.
// All client modes (TUI, Agent) communicate with the daemon through this service.
type KeleServiceServer interface {
	// Chat sends a message and receives streaming response events.
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	// Complete performs AI input completion using the small model.
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// RunCommand executes a slash command within a session.
	RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error)
	// CreateSession creates a new chat session on the daemon.
	CreateSession(context.Context, *CreateSessionRequest) (*SessionInfo, error)
	// DeleteSession removes a session.
	DeleteSession(context.Context, *DeleteSessionRequest) (*Empty, error)
	// ListSessions returns all active sessions.
	ListSessions(context.Context, *Empty) (*ListSessionsResponse, error)
	// GetStatus returns daemon status information.
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	// GetHeartbeatStatus returns heartbeat system status.
	GetHeartbeatStatus(context.Context, *Empty) (*HeartbeatStatusResponse, error)
	mustEmbedUnimplementedKeleServiceServer()
}

// UnimplementedKeleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeleServiceServer struct{}

func (UnimplementedKeleServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedKeleServiceServer) Complete(context.Context, *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedKeleServiceServer) RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedKeleServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedKeleServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedKeleServiceServer) ListSessions(context.Context, *Empty) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedKeleServiceServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedKeleServiceServer) GetHeartbeatStatus(context.Context, *Empty) (*HeartbeatStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHeartbeatStatus not implemented")
}
func (UnimplementedKeleServiceServer) mustEmbedUnimplementedKeleServiceServer() {}
func (UnimplementedKeleServiceServer) testEmbeddedByValue()                     {}

// UnsafeKeleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeleServiceServer will
// result in compilation errors.
type UnsafeKeleServiceServer interface {
	mustEmbedUnimplementedKeleServiceServer()
}

func RegisterKeleServiceServer(s grpc.ServiceRegistrar, srv KeleServiceServer) {
	// If the following call panics, it indicates UnimplementedKeleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeleService_ServiceDesc, srv)
}

func _KeleService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KeleServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeleService_ChatServer = grpc.ServerStreamingServer[ChatEvent]

func _KeleService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeleServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeleService_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeleServiceServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeleService_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeleServiceServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeleService_RunCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeleServiceServer).RunCommand(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeleService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeleServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeleService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeleServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeleService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeleServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeleService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeleServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeleService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeleServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeleService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeleServiceServer).ListSessions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeleService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeleServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeleService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeleServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeleService_GetHeartbeatStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeleServiceServer).GetHeartbeatStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeleService_GetHeartbeatStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeleServiceServer).GetHeartbeatStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// KeleService_ServiceDesc is the grpc.ServiceDesc for KeleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kele.KeleService",
	HandlerType: (*KeleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Complete",
			Handler:    _KeleService_Complete_Handler,
		},
		{
			MethodName: "RunCommand",
			Handler:    _KeleService_RunCommand_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _KeleService_CreateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _KeleService_DeleteSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _KeleService_ListSessions_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _KeleService_GetStatus_Handler,
		},
		{
			MethodName: "GetHeartbeatStatus",
			Handler:    _KeleService_GetHeartbeatStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _KeleService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kele.proto",
}
