// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: kele.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_kele_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{0}
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_kele_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{1}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// ChatEvent types: content, thinking, tool_call, tool_result, error, done
type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolName      string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolResult    string                 `protobuf:"bytes,4,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_kele_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{2}
}

func (x *ChatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ChatEvent) GetToolResult() string {
	if x != nil {
		return x.ToolResult
	}
	return ""
}

func (x *ChatEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_kele_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompleteRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestion    string                 `protobuf:"bytes,1,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_kele_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

type RunCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_kele_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{5}
}

func (x *RunCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type RunCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Quit          bool                   `protobuf:"varint,2,opt,name=quit,proto3" json:"quit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_kele_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{6}
}

func (x *RunCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunCommandResponse) GetQuit() bool {
	if x != nil {
		return x.Quit
	}
	return false
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_kele_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_kele_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MessageCount  int32                  `protobuf:"varint,3,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	HistoryCount  int32                  `protobuf:"varint,4,opt,name=history_count,json=historyCount,proto3" json:"history_count,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_kele_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{9}
}

func (x *SessionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionInfo) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionInfo) GetHistoryCount() int32 {
	if x != nil {
		return x.HistoryCount
	}
	return 0
}

func (x *SessionInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SessionInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_kele_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type StatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Version         string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Providers       []string               `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	Model           string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	SmallModel      string                 `protobuf:"bytes,5,opt,name=small_model,json=smallModel,proto3" json:"small_model,omitempty"`
	ActiveSessions  int32                  `protobuf:"varint,6,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	UptimeSeconds   int32                  `protobuf:"varint,7,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	HeartbeatActive bool                   `protobuf:"varint,8,opt,name=heartbeat_active,json=heartbeatActive,proto3" json:"heartbeat_active,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_kele_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{11}
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StatusResponse) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *StatusResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StatusResponse) GetSmallModel() string {
	if x != nil {
		return x.SmallModel
	}
	return ""
}

func (x *StatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *StatusResponse) GetUptimeSeconds() int32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetHeartbeatActive() bool {
	if x != nil {
		return x.HeartbeatActive
	}
	return false
}

type HeartbeatStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Active          bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	IntervalMinutes int32                  `protobuf:"varint,2,opt,name=interval_minutes,json=intervalMinutes,proto3" json:"interval_minutes,omitempty"`
	LastRun         string                 `protobuf:"bytes,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	LastDecision    string                 `protobuf:"bytes,4,opt,name=last_decision,json=lastDecision,proto3" json:"last_decision,omitempty"`
	TotalHeartbeats int32                  `protobuf:"varint,5,opt,name=total_heartbeats,json=totalHeartbeats,proto3" json:"total_heartbeats,omitempty"`
	ActionsTaken    int32                  `protobuf:"varint,6,opt,name=actions_taken,json=actionsTaken,proto3" json:"actions_taken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatStatusResponse) Reset() {
	*x = HeartbeatStatusResponse{}
	mi := &file_kele_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatStatusResponse) ProtoMessage() {}

func (x *HeartbeatStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kele_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatStatusResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatStatusResponse) Descriptor() ([]byte, []int) {
	return file_kele_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatStatusResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *HeartbeatStatusResponse) GetIntervalMinutes() int32 {
	if x != nil {
		return x.IntervalMinutes
	}
	return 0
}

func (x *HeartbeatStatusResponse) GetLastRun() string {
	if x != nil {
		return x.LastRun
	}
	return ""
}

func (x *HeartbeatStatusResponse) GetLastDecision() string {
	if x != nil {
		return x.LastDecision
	}
	return ""
}

func (x *HeartbeatStatusResponse) GetTotalHeartbeats() int32 {
	if x != nil {
		return x.TotalHeartbeats
	}
	return 0
}

func (x *HeartbeatStatusResponse) GetActionsTaken() int32 {
	if x != nil {
		return x.ActionsTaken
	}
	return 0
}

var File_kele_proto protoreflect.FileDescriptor

const file_kele_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"kele.proto\x12\x04kele\"\a\n" +
	"\x05Empty\"B\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\"\x8d\x01\n" +
	"\tChatEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1f\n" +
	"\vtool_result\x18\x04 \x01(\tR\n" +
	"toolResult\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"F\n" +
	"\x0fCompleteRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\"2\n" +
	"\x10CompleteResponse\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x01 \x01(\tR\n" +
	"suggestion\"L\n" +
	"\x11RunCommandRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"@\n" +
	"\x12RunCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x12\n" +
	"\x04quit\x18\x02 \x01(\bR\x04quit\"*\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xad\x01\n" +
	"\vSessionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rmessage_count\x18\x03 \x01(\x05R\fmessageCount\x12#\n" +
	"\rhistory_count\x18\x04 \x01(\x05R\fhistoryCount\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\"E\n" +
	"\x14ListSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.kele.SessionInfoR\bsessions\"\x96\x02\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1c\n" +
	"\tproviders\x18\x03 \x03(\tR\tproviders\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x1f\n" +
	"\vsmall_model\x18\x05 \x01(\tR\n" +
	"smallModel\x12'\n" +
	"\x0factive_sessions\x18\x06 \x01(\x05R\x0eactiveSessions\x12%\n" +
	"\x0euptime_seconds\x18\a \x01(\x05R\ruptimeSeconds\x12)\n" +
	"\x10heartbeat_active\x18\b \x01(\bR\x0fheartbeatActive\"\xec\x01\n" +
	"\x17HeartbeatStatusResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12)\n" +
	"\x10interval_minutes\x18\x02 \x01(\x05R\x0fintervalMinutes\x12\x19\n" +
	"\blast_run\x18\x03 \x01(\tR\alastRun\x12#\n" +
	"\rlast_decision\x18\x04 \x01(\tR\flastDecision\x12)\n" +
	"\x10total_heartbeats\x18\x05 \x01(\x05R\x0ftotalHeartbeats\x12#\n" +
	"\ractions_taken\x18\x06 \x01(\x05R\factionsTaken2\xdc\x03\n" +
	"\vKeleService\x12,\n" +
	"\x04Chat\x12\x11.kele.ChatRequest\x1a\x0f.kele.ChatEvent0\x01\x129\n" +
	"\bComplete\x12\x15.kele.CompleteRequest\x1a\x16.kele.CompleteResponse\x12?\n" +
	"\n" +
	"RunCommand\x12\x17.kele.RunCommandRequest\x1a\x18.kele.RunCommandResponse\x12>\n" +
	"\rCreateSession\x12\x1a.kele.CreateSessionRequest\x1a\x11.kele.SessionInfo\x128\n" +
	"\rDeleteSession\x12\x1a.kele.DeleteSessionRequest\x1a\v.kele.Empty\x127\n" +
	"\fListSessions\x12\v.kele.Empty\x1a\x1a.kele.ListSessionsResponse\x12.\n" +
	"\tGetStatus\x12\v.kele.Empty\x1a\x14.kele.StatusResponse\x12@\n" +
	"\x12GetHeartbeatStatus\x12\v.kele.Empty\x1a\x1d.kele.HeartbeatStatusResponseB+Z)github.com/BlakeLiAFK/kele/internal/protob\x06proto3"

var (
	file_kele_proto_rawDescOnce sync.Once
	file_kele_proto_rawDescData []byte
)

func file_kele_proto_rawDescGZIP() []byte {
	file_kele_proto_rawDescOnce.Do(func() {
		file_kele_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kele_proto_rawDesc), len(file_kele_proto_rawDesc)))
	})
	return file_kele_proto_rawDescData
}

var file_kele_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_kele_proto_goTypes = []any{
	(*Empty)(nil),                   // 0: kele.Empty
	(*ChatRequest)(nil),             // 1: kele.ChatRequest
	(*ChatEvent)(nil),               // 2: kele.ChatEvent
	(*CompleteRequest)(nil),         // 3: kele.CompleteRequest
	(*CompleteResponse)(nil),        // 4: kele.CompleteResponse
	(*RunCommandRequest)(nil),       // 5: kele.RunCommandRequest
	(*RunCommandResponse)(nil),      // 6: kele.RunCommandResponse
	(*CreateSessionRequest)(nil),    // 7: kele.CreateSessionRequest
	(*DeleteSessionRequest)(nil),    // 8: kele.DeleteSessionRequest
	(*SessionInfo)(nil),             // 9: kele.SessionInfo
	(*ListSessionsResponse)(nil),    // 10: kele.ListSessionsResponse
	(*StatusResponse)(nil),          // 11: kele.StatusResponse
	(*HeartbeatStatusResponse)(nil), // 12: kele.HeartbeatStatusResponse
}
var file_kele_proto_depIdxs = []int32{
	9,  // 0: kele.ListSessionsResponse.sessions:type_name -> kele.SessionInfo
	1,  // 1: kele.KeleService.Chat:input_type -> kele.ChatRequest
	3,  // 2: kele.KeleService.Complete:input_type -> kele.CompleteRequest
	5,  // 3: kele.KeleService.RunCommand:input_type -> kele.RunCommandRequest
	7,  // 4: kele.KeleService.CreateSession:input_type -> kele.CreateSessionRequest
	8,  // 5: kele.KeleService.DeleteSession:input_type -> kele.DeleteSessionRequest
	0,  // 6: kele.KeleService.ListSessions:input_type -> kele.Empty
	0,  // 7: kele.KeleService.GetStatus:input_type -> kele.Empty
	0,  // 8: kele.KeleService.GetHeartbeatStatus:input_type -> kele.Empty
	2,  // 9: kele.KeleService.Chat:output_type -> kele.ChatEvent
	4,  // 10: kele.KeleService.Complete:output_type -> kele.CompleteResponse
	6,  // 11: kele.KeleService.RunCommand:output_type -> kele.RunCommandResponse
	9,  // 12: kele.KeleService.CreateSession:output_type -> kele.SessionInfo
	0,  // 13: kele.KeleService.DeleteSession:output_type -> kele.Empty
	10, // 14: kele.KeleService.ListSessions:output_type -> kele.ListSessionsResponse
	11, // 15: kele.KeleService.GetStatus:output_type -> kele.StatusResponse
	12, // 16: kele.KeleService.GetHeartbeatStatus:output_type -> kele.HeartbeatStatusResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_kele_proto_init() }
func file_kele_proto_init() {
	if File_kele_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kele_proto_rawDesc), len(file_kele_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kele_proto_goTypes,
		DependencyIndexes: file_kele_proto_depIdxs,
		MessageInfos:      file_kele_proto_msgTypes,
	}.Build()
	File_kele_proto = out.File
	file_kele_proto_goTypes = nil
	file_kele_proto_depIdxs = nil
}
